const EDEXCEL_IGCSE_DATA = [
    {"date": "17/05/2022","qualification": "IGCSE","examCode": "4AC1 01","subject": "Accounting","title": "Paper 1: Introduction to Bookkeeping and Accounting","amPM": "PM","duration": "2h 00m"},
{"date": "14/06/2022","qualification": "IGCSE","examCode": "4AC1 02","subject": "Accounting","title": "Paper 2: Financial Statements","amPM": "AM","duration": "1h 15m"},
{"date": "31/05/2022","qualification": "IGCSE","examCode": "4AA1 01","subject": "Arabic ","title": "Paper 1: Reading, Summary and Grammar","amPM": "AM","duration": "2h 15m"},    
{"date": "16/06/2022","qualification": "IGCSE","examCode": "4AA1 02","subject": "Arabic ","title": "Paper 2: Writing","amPM": "AM","duration": "1h 30m"},
{"date": "30/05/2022","qualification": "IGCSE","examCode": "4BA0 01","subject": "Bangla","title": "Paper 1: Reading, Writing and Translation","amPM": "PM","duration": "2h 30m"}, 
{"date": "19/05/2022","qualification": "IGCSE","examCode": "4BN1 01","subject": "Bangladesh Studies","title": "Paper 1: History and culture of Bangladesh","amPM": "PM","duration": "1h 30m"},
{"date": "31/05/2022","qualification": "IGCSE","examCode": "4BN1 02","subject": "Bangladesh Studies","title": "Paper 2: The landscape, people and economy of Bangladesh","amPM": "PM","duration": "1h 30m"},
{"date": "17/05/2022","qualification": "IGCSE","examCode": "4BI1 1B","subject": "Biology","title": "Paper: 1B","amPM": "AM","duration": "2h 00m"},
{"date": "15/06/2022","qualification": "IGCSE","examCode": "4BI1 2B","subject": "Biology","title": "Paper: 2B","amPM": "AM","duration": "1h 15m"},
{"date": "19/05/2022","qualification": "IGCSE","examCode": "4BS1 01","subject": "Business ","title": "Paper 1: Investigating small businesses","amPM": "PM","duration": "1h 30m"},{"date": "13/06/2022","qualification": "IGCSE","examCode": "4BS1 02","subject": "Business ","title": "Paper 2: Investigating large businesses","amPM": "AM","duration": "1h 30m"},{"date": "27/05/2022","qualification": "IGCSE","examCode": "4CH1 1C","subject": "Chemistry","title": "Paper: 1C","amPM": "AM","duration": "2h 00m"},
{"date": "20/06/2022","qualification": "IGCSE","examCode": "4CH1 2C","subject": "Chemistry","title": "Paper: 2C","amPM": "AM","duration": "1h 15m"},
{"date": "25/05/2022","qualification": "IGCSE","examCode": "4CN1 01","subject": "Chinese","title": "Paper 1: Listening","amPM": "PM","duration": "0h 35m"},
{"date": "25/05/2022","qualification": "IGCSE","examCode": "4CN1 02","subject": "Chinese","title": "Paper 2: Reading and Writing ","amPM": "PM","duration": "1h 45m"},
{"date": "01/06/2022","qualification": "IGCSE","examCode": "4CM1 01","subject": "Commerce","title": "Paper 1: Commercial operations and associated risks","amPM": "AM","duration": "1h 30m"},
{"date": "16/06/2022","qualification": "IGCSE","examCode": "4CM1 02","subject": "Commerce","title": "Paper 2: Facilitating commerical operations","amPM": "PM","duration": "1h 30m"},
{"date": "20/05/2022","qualification": "IGCSE","examCode": "4CP0 01","subject": "Computer Science","title": "Paper 1: Principles of Computer Science","amPM": "PM","duration": "2h 00m"},
{"date": "06/06/2022","qualification": "IGCSE","examCode": "4CP0 02","subject": "Computer Science","title": "Paper 2: Application of Computational Thinking","amPM": "N/A","duration": "3h 00m"},
{"date": "07/06/2022","qualification": "IGCSE","examCode": "4CP0 02","subject": "Computer Science","title": "Paper 2: Application of Computational Thinking","amPM": "N/A","duration": "3h 00m"},
{"date": "08/06/2022","qualification": "IGCSE","examCode": "4CP0 02","subject": "Computer Science","title": "Paper 2: Application of Computational Thinking","amPM": "N/A","duration": "3h 00m"},
{"date": "24/05/2022","qualification": "IGCSE","examCode": "4EC1 01","subject": "Economics","title": "Paper 1: Microeconomics and Business Economics","amPM": "PM","duration": "1h 30m"},
{"date": "14/06/2022","qualification": "IGCSE","examCode": "4EC1 02","subject": "Economics","title": "Paper 2: Macroeconomics and the Global Economy","amPM": "PM","duration": "1h 30m"},
{"date": "16/05/2022","qualification": "IGCSE","examCode": "4ES1 01","subject": "English as a Second Language","title": "Paper 1: Reading and Writing","amPM": "PM","duration": "2h 00m"},
{"date": "06/06/2022","qualification": "IGCSE","examCode": "4ES1 02","subject": "English as a Second Language","title": "Paper 2: Listening","amPM": "AM","duration": "0h 55m"},  
{"date": "18/05/2022","qualification": "IGCSE","examCode": "4EA1 01","subject": "English Language A","title": "Paper 1: Non-fiction Texts and Transactional Writing","amPM": "AM","duration": "2h 15m"},
{"date": "10/06/2022","qualification": "IGCSE","examCode": "4EA1 02","subject": "English Language A","title": "Paper 2: Poetry and Prose Texts and Imaginative Writing","amPM": "AM","duration": "1h 30m"},
{"date": "18/05/2022","qualification": "IGCSE","examCode": "4EB1 01","subject": "English Language B","title": "Paper 1","amPM": "AM","duration": "3h 00m"},
{"date": "25/05/2022","qualification": "IGCSE","examCode": "4ET1 01","subject": "English Literature","title": "Paper 1: Poetry and Modern Prose","amPM": "AM","duration": "1h 20m"},
{"date": "08/06/2022","qualification": "IGCSE","examCode": "4ET1 02","subject": "English Literature","title": "Paper 2: Modern Drama and Literary Heritage Texts","amPM": "AM","duration": "1h 30m"},
{"date": "24/05/2022","qualification": "IGCSE","examCode": "4FR1 01","subject": "French","title": "Paper 1: Listening ","amPM": "AM","duration": "0h 35m"},
{"date": "24/05/2022","qualification": "IGCSE","examCode": "4FR1 02","subject": "French","title": "Paper 2: Reading and Writing ","amPM": "AM","duration": "1h 45m"},
{"date": "26/05/2022","qualification": "IGCSE","examCode": "4PM1 01","subject": "Further Pure Mathematics","title": "Paper 1","amPM": "PM","duration": "2h 00m"},
{"date": "17/06/2022","qualification": "IGCSE","examCode": "4PM1 02","subject": "Further Pure Mathematics","title": "Paper 2","amPM": "AM","duration": "2h 00m"},
{"date": "23/05/2022","qualification": "IGCSE","examCode": "4GE1 01","subject": "Geography","title": "Paper 1: Physical geography","amPM": "AM","duration": "1h 10m"},
{"date": "07/06/2022","qualification": "IGCSE","examCode": "4GE1 02","subject": "Geography","title": "Paper 2: Human geography","amPM": "PM","duration": "1h 45m"},
{"date": "18/05/2022","qualification": "IGCSE","examCode": "4GN1 01","subject": "German","title": "Paper 1: Listening ","amPM": "PM","duration": "0h 35m"},
{"date": "18/05/2022","qualification": "IGCSE","examCode": "4GN1 02","subject": "German","title": "Paper 2: Reading and Writing ","amPM": "PM","duration": "1h 45m"},
{"date": "23/05/2022","qualification": "IGCSE","examCode": "4GL1 01","subject": "Global Citizenship","title": "Paper 1","amPM": "PM","duration": "2h 30m"},
{"date": "01/06/2022","qualification": "IGCSE","examCode": "4GK1 01","subject": "Greek (First Language)","title": "Paper 1: Reading, Summary and Grammar ","amPM": "PM","duration": "2h 15m"},
{"date": "15/06/2022","qualification": "IGCSE","examCode": "4GK1 02","subject": "Greek (First Language)","title": "Paper 2: Writing ","amPM": "PM","duration": "1h 30m"},
{"date": "19/05/2022","qualification": "IGCSE","examCode": "4HI1 1A","subject": "History","title": "Paper 1: Depth Studies A","amPM": "AM","duration": "1h 30m"},
{"date": "19/05/2022","qualification": "IGCSE","examCode": "4HI1 1B","subject": "History","title": "Paper 1: Depth Studies B","amPM": "AM","duration": "0h 45m"},
{"date": "09/06/2022","qualification": "IGCSE","examCode": "4HI1 2A","subject": "History","title": "Paper 2: Investigation ","amPM": "AM","duration": "0h 45m"},
{"date": "09/06/2022","qualification": "IGCSE","examCode": "4HI1 2B","subject": "History","title": "Paper 2: Investigation and Breadth Studies","amPM": "AM","duration": "1h 30m"},
{"date": "17/05/2022","qualification": "IGCSE","examCode": "4HB1 01","subject": "Human Biology","title": "Paper 01","amPM": "PM","duration": "1h 45m"},
{"date": "06/06/2022","qualification": "IGCSE","examCode": "4HB1 02","subject": "Human Biology","title": "Paper 02","amPM": "PM","duration": "1h 45m"},
{"date": "16/05/2022","qualification": "IGCSE","examCode": "4IT1 01","subject": "Information And Communication Technology (ICT)","title": "Paper 1: Written Paper","amPM": "PM","duration": "1h 30m"},
{"date": "23/05/2022","qualification": "IGCSE","examCode": "4IT1 02","subject": "Information And Communication Technology (ICT)","title": "Paper 2: Practical Exam","amPM": "N/A","duration": "3h 00m"},
{"date": "24/05/2022","qualification": "IGCSE","examCode": "4IT1 02","subject": "Information And Communication Technology (ICT)","title": "Paper 2: Practical Exam","amPM": "N/A","duration": "3h 00m"},
{"date": "25/05/2022","qualification": "IGCSE","examCode": "4IT1 02","subject": "Information And Communication Technology (ICT)","title": "Paper 2: Practical Exam","amPM": "N/A","duration": "3h 00m"},
{"date": "26/05/2022","qualification": "IGCSE","examCode": "4IT1 02","subject": "Information And Communication Technology (ICT)","title": "Paper 2: Practical Exam","amPM": "N/A","duration": "3h 00m"},
{"date": "27/05/2022","qualification": "IGCSE","examCode": "4IT1 02","subject": "Information And Communication Technology (ICT)","title": "Paper 2: Practical Exam","amPM": "N/A","duration": "3h 00m"},
{"date": "30/05/2022","qualification": "IGCSE","examCode": "4IS1 01","subject": "Islamic Studies","title": "Paper 1: Islamic Studies","amPM": "AM","duration": "2h 30m"},
{"date": "20/05/2022","qualification": "IGCSE","examCode": "4MA1 1F","subject": "Mathematics A","title": "Paper 1F Foundation Tier","amPM": "AM","duration": "2h 00m"},
{"date": "20/05/2022","qualification": "IGCSE","examCode": "4MA1 1H","subject": "Mathematics A","title": "Paper 1H Higher Tier","amPM": "AM","duration": "2h 00m"},
{"date": "07/06/2022","qualification": "IGCSE","examCode": "4MA1 2F","subject": "Mathematics A","title": "Paper 2F Foundation Tier","amPM": "AM","duration": "2h 00m"},
{"date": "07/06/2022","qualification": "IGCSE","examCode": "4MA1 2H","subject": "Mathematics A","title": "Paper 2H Higher Tier","amPM": "AM","duration": "2h 00m"},
{"date": "20/05/2022","qualification": "IGCSE","examCode": "4MB1 01","subject": "Mathematics B","title": "Paper 1","amPM": "AM","duration": "1h 30m"},
{"date": "07/06/2022","qualification": "IGCSE","examCode": "4MB1 02","subject": "Mathematics B","title": "Paper 2","amPM": "AM","duration": "2h 30m"},
{"date": "01/06/2022","qualification": "IGCSE","examCode": "4PA1 01","subject": "Pakistan Studies","title": "Paper 1: History and culture of Pakistan","amPM": "AM","duration": "1h 30m"},
{"date": "13/06/2022","qualification": "IGCSE","examCode": "4PA1 02","subject": "Pakistan Studies","title": "Paper 2: The landscape, people and economy of Pakistan","amPM": "PM","duration": "1h 30m"},
{"date": "09/06/2022","qualification": "IGCSE","examCode": "4PH1 1P","subject": "Physics","title": "Paper: 1P","amPM": "PM","duration": "2h 00m"},
{"date": "23/06/2022","qualification": "IGCSE","examCode": "4PH1 2P","subject": "Physics","title": "Paper: 2P","amPM": "AM","duration": "1h 15m"},
{"date": "16/05/2022","qualification": "IGCSE","examCode": "4RS1 01","subject": "Religious Studies","title": "Paper 1: Beliefs and Values","amPM": "AM","duration": "1h 45m"},    
{"date": "08/06/2022","qualification": "IGCSE","examCode": "4RS1 02","subject": "Religious Studies","title": "Paper 2: The Religious Community","amPM": "PM","duration": "1h 30m"},
{"date": "17/05/2022","qualification": "IGCSE","examCode": "4SD0 1B","subject": "Science (Double Award)","title": "Paper: 1B","amPM": "AM","duration": "2h 00m"},
{"date": "09/06/2022","qualification": "IGCSE","examCode": "4SD0 1P","subject": "Science (Double Award)","title": "Paper: 1P","amPM": "PM","duration": "2h 00m"},
{"date": "27/05/2022","qualification": "IGCSE","examCode": "4SD0 1C","subject": "Science (Double Award)","title": "Paper: 1C","amPM": "AM","duration": "2h 00m"},
{"date": "23/06/2022","qualification": "IGCSE","examCode": "4SS0 1P","subject": "Science (Single Award)","title": "Paper: 1P","amPM": "AM","duration": "1h 10m"},
{"date": "15/06/2022","qualification": "IGCSE","examCode": "4SS0 1B","subject": "Science (Single Award)","title": "Paper: 1B","amPM": "AM","duration": "1h 10m"},
{"date": "20/06/2022","qualification": "IGCSE","examCode": "4SS0 1C","subject": "Science (Single Award)","title": "Paper: 1C","amPM": "AM","duration": "1h 10m"},
{"date": "17/06/2022","qualification": "IGCSE","examCode": "4SI1 01","subject": "Sinhala","title": "Paper 1: Reading, Writing and Translation","amPM": "PM","duration": "2h 30m"},{"date": "26/05/2022","qualification": "IGCSE","examCode": "4SP1 01","subject": "Spanish","title": "Paper 1: Listening ","amPM": "AM","duration": "0h 35m"},
{"date": "26/05/2022","qualification": "IGCSE","examCode": "4SP1 02","subject": "Spanish","title": "Paper 2: Reading and Writing ","amPM": "AM","duration": "1h 45m"},
{"date": "01/06/2022","qualification": "IGCSE","examCode": "4SW1 01","subject": "Swahili","title": "Paper 1: Reading, Writing and Translation","amPM": "PM","duration": "2h 15m"},{"date": "01/06/2022","qualification": "IGCSE","examCode": "4SW1 02","subject": "Swahili","title": "Paper 2: Listening","amPM": "PM","duration": "0h 35m"},
{"date": "10/06/2022","qualification": "IGCSE","examCode": "4TA1 01","subject": "Tamil","title": "Paper 1: Reading, Writing and Translation","amPM": "PM","duration": "2h 30m"}
];

const EDEXCEL_GCSE_DATA = [
    {"date": "24/05/2022","qualification": "GCSE","examCode": "1AA0 1F","subject": "Arabic","title": "Paper 1: Listening and understanding in Arabic Foundation Tier","amPM": "AM","duration": "0h 35m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1AA0 1H","subject": "Arabic","title": "Paper 1: Listening and understanding in Arabic Higher Tier","amPM": "AM","duration": "0h 45m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1AA0 3F","subject": "Arabic","title": "Paper 3: Reading and understanding in Arabic Foundation Tier","amPM": "AM","duration": "0h 50m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1AA0 3H","subject": "Arabic","title": "Paper 3: Reading and understanding in Arabic Higher Tier","amPM": "AM","duration": "1h 05m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1AA0 4F","subject": "Arabic","title": "Paper 4: Writing in Arabic Foundation Tier","amPM": "PM","duration": "1h 20m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1AA0 4H","subject": "Arabic","title": "Paper 4: Writing in Arabic Higher Tier","amPM": "PM","duration": "1h 25m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1AS0 01","subject": "Astronomy","title": "Paper 1: Naked-eye Astronomy","amPM": "PM","duration": "1h 45m"},
{"date": "28/06/2022","qualification": "GCSE","examCode": "1AS0 02","subject": "Astronomy","title": "Paper 2: Telescopic Astronomy","amPM": "AM","duration": "1h 45m"},
{"date": "25/05/2022","qualification": "GCSE","examCode": "1BH0 01","subject": "Biblical Hebrew","title": "Component 1: Language","amPM": "PM","duration": "2h 00m"},
{"date": "16/06/2022","qualification": "GCSE","examCode": "1BH0 02","subject": "Biblical Hebrew","title": "Component 2: Literature","amPM": "PM","duration": "2h 00m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1BI0 1F","subject": "Biology","title": "Paper 1 Foundation Tier","amPM": "AM","duration": "1h 45m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1BI0 1H","subject": "Biology","title": "Paper 1 Higher Tier","amPM": "AM","duration": "1h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1BI0 2F","subject": "Biology","title": "Paper 2 Foundation Tier","amPM": "AM","duration": "1h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1BI0 2H","subject": "Biology","title": "Paper 2 Higher Tier","amPM": "AM","duration": "1h 45m"},
{"date": "20/05/2022","qualification": "GCSE","examCode": "1BS0 01","subject": "Business","title": "Paper 1: Investigating Small Business","amPM": "PM","duration": "1h 30m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1BS0 02","subject": "Business","title": "Paper 2: Building a Business","amPM": "PM","duration": "1h 30m"},
{"date": "27/05/2022","qualification": "GCSE","examCode": "1CH0 1F","subject": "Chemistry","title": "Paper 1 Foundation Tier","amPM": "AM","duration": "1h 45m"},
{"date": "27/05/2022","qualification": "GCSE","examCode": "1CH0 1H","subject": "Chemistry","title": "Paper 1 Higher Tier","amPM": "AM","duration": "1h 45m"},
{"date": "20/06/2022","qualification": "GCSE","examCode": "1CH0 2F","subject": "Chemistry","title": "Paper 2 Foundation Tier","amPM": "AM","duration": "1h 45m"},
{"date": "20/06/2022","qualification": "GCSE","examCode": "1CH0 2H","subject": "Chemistry","title": "Paper 2 Higher Tier","amPM": "AM","duration": "1h 45m"},
{"date": "20/05/2022","qualification": "GCSE","examCode": "1CN0 1F","subject": "Chinese","title": "Paper 1: Listening and understanding in Chinese Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "20/05/2022","qualification": "GCSE","examCode": "1CN0 1H","subject": "Chinese","title": "Paper 1: Listening and understanding in Chinese Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "20/05/2022","qualification": "GCSE","examCode": "1CN0 3F","subject": "Chinese","title": "Paper 3: Reading and understanding in Chinese Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "20/05/2022","qualification": "GCSE","examCode": "1CN0 3H","subject": "Chinese","title": "Paper 3: Reading and understanding in Chinese Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1CN0 4F","subject": "Chinese","title": "Paper 4: Writing in Chinese Foundation Tier","amPM": "AM","duration": "1h 20m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1CN0 4H","subject": "Chinese","title": "Paper 4: Writing in Chinese Higher Tier","amPM": "AM","duration": "1h 25m"},
{"date": "23/05/2022","qualification": "GCSE","examCode": "1CS0 01","subject": "Citizenship Studies","title": "Paper 1","amPM": "PM","duration": "1h 45m"},
{"date": "14/06/2022","qualification": "GCSE","examCode": "1CS0 02","subject": "Citizenship Studies","title": "Paper 2","amPM": "PM","duration": "1h 45m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1SC0 1BF","subject": "Combined Science","title": "Paper 1: Biology 1 Foundation Tier","amPM": "AM","duration": "1h 10m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1SC0 1BH","subject": "Combined Science","title": "Paper 1: Biology 1 Higher Tier","amPM": "AM","duration": "1h 10m"},
{"date": "27/05/2022","qualification": "GCSE","examCode": "1SC0 1CF","subject": "Combined Science","title": "Paper 2: Chemistry 1 Foundation Tier","amPM": "AM","duration": "1h 10m"},
{"date": "27/05/2022","qualification": "GCSE","examCode": "1SC0 1CH","subject": "Combined Science","title": "Paper 2: Chemistry 1 Higher Tier","amPM": "AM","duration": "1h 10m"},
{"date": "09/06/2022","qualification": "GCSE","examCode": "1SC0 1PF","subject": "Combined Science","title": "Paper 3: Physics 1 Foundation Tier","amPM": "PM","duration": "1h 10m"},
{"date": "09/06/2022","qualification": "GCSE","examCode": "1SC0 1PH","subject": "Combined Science","title": "Paper 3: Physics 1 Higher Tier","amPM": "PM","duration": "1h 10m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1SC0 2BF","subject": "Combined Science","title": "Paper 4: Biology 2 Foundation Tier","amPM": "AM","duration": "1h 10m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1SC0 2BH","subject": "Combined Science","title": "Paper 4: Biology 2 Higher Tier","amPM": "AM","duration": "1h 10m"},
{"date": "20/06/2022","qualification": "GCSE","examCode": "1SC0 2CF","subject": "Combined Science","title": "Paper 5: Chemistry 2 Foundation Tier","amPM": "AM","duration": "1h 10m"},
{"date": "20/06/2022","qualification": "GCSE","examCode": "1SC0 2CH","subject": "Combined Science","title": "Paper 5: Chemistry 2 Higher Tier","amPM": "AM","duration": "1h 10m"},
{"date": "23/06/2022","qualification": "GCSE","examCode": "1SC0 2PF","subject": "Combined Science","title": "Paper 6: Physics 2 Foundation Tier","amPM": "AM","duration": "1h 10m"},
{"date": "23/06/2022","qualification": "GCSE","examCode": "1SC0 2PH","subject": "Combined Science","title": "Paper 6: Physics 2 Higher Tier","amPM": "AM","duration": "1h 10m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "1CP2 01","subject": "Computer Science","title": "Paper 1: Principles of Computer Science","amPM": "PM","duration": "1h 30m"},
{"date": "27/05/2022","qualification": "GCSE","examCode": "1CP2 02","subject": "Computer Science","title": "Paper 2: Application of Computational Thinking (Onscreen using an Integrated Development Environment (IDE) of choice)","amPM": "PM","duration": "2h 00m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1DT0 1A","subject": "Deisgn And Technology ","title": "Component 1: Metals","amPM": "PM","duration": "1h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1DT0 1B","subject": "Deisgn And Technology ","title": "Component 1: Papers and boards","amPM": "PM","duration": "1h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1DT0 1C","subject": "Deisgn And Technology ","title": "Component 1: Polymers","amPM": "PM","duration": "1h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1DT0 1D","subject": "Deisgn And Technology ","title": "Component 1: Systems","amPM": "PM","duration": "1h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1DT0 1E","subject": "Deisgn And Technology ","title": "Component 1: Textiles","amPM": "PM","duration": "1h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1DT0 1F","subject": "Deisgn And Technology ","title": "Component 1: Timbers","amPM": "PM","duration": "1h 45m"},
{"date": "19/05/2022","qualification": "GCSE","examCode": "1DR0 03","subject": "Drama","title": "Component 3: Theatre Makers in Practice","amPM": "PM","duration": "1h 45m"},
{"date": "18/05/2022","qualification": "GCSE","examCode": "1EN0 01","subject": "English Language","title": "Paper 1: Fiction and Imaginative Writing","amPM": "AM","duration": "1h 45m"},
{"date": "10/06/2022","qualification": "GCSE","examCode": "1EN0 02","subject": "English Language","title": "Paper 2: Non-Fiction and Transactional Writing","amPM": "AM","duration": "2h 05m"},
{"date": "18/05/2022","qualification": "GCSE","examCode": "1EN2 01","subject": "English Language 2.0","title": "Paper 1: Non-Fiction Texts","amPM": "AM","duration": "1h 55m"},
{"date": "10/06/2022","qualification": "GCSE","examCode": "1EN2 02","subject": "English Language 2.0","title": "Paper 2: Contemporary Texts","amPM": "AM","duration": "1h 55m"},
{"date": "25/05/2022","qualification": "GCSE","examCode": "1ET0 01","subject": "English Literature","title": "Paper 1: Shakespeare and Post-1914 Literature","amPM": "AM","duration": "1h 45m"},
{"date": "08/06/2022","qualification": "GCSE","examCode": "1ET0 02N","subject": "English Literature","title": "Paper 2: 19th Century Novel","amPM": "AM","duration": "1h 20m"},
{"date": "08/06/2022","qualification": "GCSE","examCode": "1ET0 02P","subject": "English Literature","title": "Paper 2: Poetry since 1789","amPM": "AM","duration": "1h 20m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1FR0 1F","subject": "French","title": "Paper 1: Listening and understanding in French Foundation Tier","amPM": "AM","duration": "0h 35m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1FR0 1H","subject": "French","title": "Paper 1: Listening and understanding in French Higher Tier","amPM": "AM","duration": "0h 45m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1FR0 3F","subject": "French","title": "Paper 3: Reading and understanding in French Foundation Tier","amPM": "AM","duration": "0h 45m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1FR0 3H","subject": "French","title": "Paper 3: Reading and understanding in French Higher Tier","amPM": "AM","duration": "1h 00m"},
{"date": "16/06/2022","qualification": "GCSE","examCode": "1FR0 4F","subject": "French","title": "Paper 4: Writing in French Foundation Tier","amPM": "PM","duration": "1h 15m"},
{"date": "16/06/2022","qualification": "GCSE","examCode": "1FR0 4H","subject": "French","title": "Paper 4: Writing in French Higher Tier","amPM": "PM","duration": "1h 20m"},
{"date": "23/05/2022","qualification": "GCSE","examCode": "1GA0 01","subject": "Geography A","title": "Paper 1: The Physical Environment","amPM": "AM","duration": "1h 30m"},
{"date": "07/06/2022","qualification": "GCSE","examCode": "1GA0 02","subject": "Geography A","title": "Paper 2: The Human Environment","amPM": "PM","duration": "1h 30m"},
{"date": "14/06/2022","qualification": "GCSE","examCode": "1GA0 03","subject": "Geography A","title": "Paper 3: Geographical Investigations: Fieldwork and UK Challenges","amPM": "AM","duration": "1h 30m"},
{"date": "23/05/2022","qualification": "GCSE","examCode": "1GB0 01","subject": "Geography B","title": "Paper 1: Global Geographical Issues","amPM": "AM","duration": "1h 30m"},
{"date": "07/06/2022","qualification": "GCSE","examCode": "1GB0 02","subject": "Geography B","title": "Paper 2: UK Geographical Issues","amPM": "PM","duration": "1h 30m"},
{"date": "14/06/2022","qualification": "GCSE","examCode": "1GB0 03","subject": "Geography B","title": "Paper 3: People and Environment Issues – Making Geographical Decisions","amPM": "AM","duration": "1h 30m"},
{"date": "18/05/2022","qualification": "GCSE","examCode": "1GN0 1F","subject": "German","title": "Paper 1: Listening and understanding in German Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "18/05/2022","qualification": "GCSE","examCode": "1GN0 1H","subject": "German","title": "Paper 1: Listening and understanding in German Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "18/05/2022","qualification": "GCSE","examCode": "1GN0 3F","subject": "German","title": "Paper 3: Reading and understanding in German Foundation Tier","amPM": "PM","duration": "0h 45m"},
{"date": "18/05/2022","qualification": "GCSE","examCode": "1GN0 3H","subject": "German","title": "Paper 3: Reading and understanding in German Higher Tier","amPM": "PM","duration": "1h 00m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1GN0 4F","subject": "German","title": "Paper 4: Writing in German Foundation Tier","amPM": "AM","duration": "1h 15m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1GN0 4H","subject": "German","title": "Paper 4: Writing in German Higher Tier","amPM": "AM","duration": "1h 20m"},
{"date": "25/05/2022","qualification": "GCSE","examCode": "1GK0 1F","subject": "Greek","title": "Paper 1: Listening and understanding in Greek Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "25/05/2022","qualification": "GCSE","examCode": "1GK0 1H","subject": "Greek","title": "Paper 1: Listening and understanding in Greek Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "25/05/2022","qualification": "GCSE","examCode": "1GK0 3F","subject": "Greek","title": "Paper 3: Reading and understanding in Greek Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "25/05/2022","qualification": "GCSE","examCode": "1GK0 3H","subject": "Greek","title": "Paper 3: Reading and understanding in Greek Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1GK0 4F","subject": "Greek","title": "Paper 4: Writing in Greek Foundation Tier","amPM": "PM","duration": "1h 20m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1GK0 4H","subject": "Greek","title": "Paper 4: Writing in Greek Higher Tier","amPM": "PM","duration": "1h 25m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1GU0 1F","subject": "Gujarati","title": "Paper 1: Listening and understanding in Gujarati Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1GU0 1H","subject": "Gujarati","title": "Paper 1: Listening and understanding in Gujarati Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1GU0 3F","subject": "Gujarati","title": "Paper 3: Reading and understanding in Gujarati Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1GU0 3H","subject": "Gujarati","title": "Paper 3: Reading and understanding in Gujarati Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "24/06/2022","qualification": "GCSE","examCode": "1GU0 4F","subject": "Gujarati","title": "Paper 4: Writing in Gujarati Foundation Tier","amPM": "AM","duration": "1h 20m"},
{"date": "24/06/2022","qualification": "GCSE","examCode": "1GU0 4H","subject": "Gujarati","title": "Paper 4: Writing in Gujarati Higher Tier","amPM": "AM","duration": "1h 25m"},
{"date": "19/05/2022","qualification": "GCSE","examCode": "1HIA 10-13","subject": "History","title": "Paper 1: Thematic study and historic environment","amPM": "AM","duration": "1h 15m"},
{"date": "16/06/2022","qualification": "GCSE","examCode": "1HIA B1-B4","subject": "History","title": "Paper 2: British depth study","amPM": "AM","duration": "0h 55m"},
{"date": "21/06/2022","qualification": "GCSE","examCode": "1HIA P1-P5","subject": "History","title": "Paper 2: Period study","amPM": "AM","duration": "0h 55m"},
{"date": "09/06/2022","qualification": "GCSE","examCode": "1HIA 30-33","subject": "History","title": "Paper 3: Modern depth study","amPM": "AM","duration": "1h 20m"},
{"date": "16/06/2022","qualification": "GCSE","examCode": "1HIB B1-B4","subject": "History","title": "Paper 2: British depth study","amPM": "AM","duration": "0h 55m"},
{"date": "21/06/2022","qualification": "GCSE","examCode": "1HIB P1-P5","subject": "History","title": "Paper 2: Period study","amPM": "AM","duration": "0h 55m"},
{"date": "09/06/2022","qualification": "GCSE","examCode": "1HIB 30-33","subject": "History","title": "Paper 3: Modern depth study","amPM": "AM","duration": "1h 20m"},
{"date": "19/05/2022","qualification": "GCSE","examCode": "1IN0 1F","subject": "Italian","title": "Paper 1: Listening and understanding in Italian Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "19/05/2022","qualification": "GCSE","examCode": "1IN0 1H","subject": "Italian","title": "Paper 1: Listening and understanding in Italian Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "19/05/2022","qualification": "GCSE","examCode": "1IN0 3F","subject": "Italian","title": "Paper 3: Reading and understanding in Italian Foundation Tier","amPM": "PM","duration": "0h 45m"},
{"date": "19/05/2022","qualification": "GCSE","examCode": "1IN0 3H","subject": "Italian","title": "Paper 3: Reading and understanding in Italian Higher Tier","amPM": "PM","duration": "1h 00m"},
{"date": "14/06/2022","qualification": "GCSE","examCode": "1IN0 4F","subject": "Italian","title": "Paper 4: Writing in Italian Foundation Tier","amPM": "PM","duration": "1h 15m"},
{"date": "14/06/2022","qualification": "GCSE","examCode": "1IN0 4H","subject": "Italian","title": "Paper 4: Writing in Italian Higher Tier","amPM": "PM","duration": "1h 20m"},
{"date": "10/06/2022","qualification": "GCSE","examCode": "1JA0 1F","subject": "Japanese","title": "Paper 1: Listening and understanding in Japanese Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "10/06/2022","qualification": "GCSE","examCode": "1JA0 1H","subject": "Japanese","title": "Paper 1: LIstening and understanding in Japanese Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "10/06/2022","qualification": "GCSE","examCode": "1JA0 3F","subject": "Japanese","title": "Paper 3: Reading and understanding in Japanese Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "10/06/2022","qualification": "GCSE","examCode": "1JA0 3H","subject": "Japanese","title": "Paper 3: Reading and understanding in Japanese Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "20/06/2022","qualification": "GCSE","examCode": "1JA0 4F","subject": "Japanese","title": "Paper 4: Writing in Japanese Foundation Tier","amPM": "PM","duration": "1h 20m"},
{"date": "20/06/2022","qualification": "GCSE","examCode": "1JA0 4H","subject": "Japanese","title": "Paper 4: Writing in Japanese Higher Tier","amPM": "PM","duration": "1h 25m"},
{"date": "20/05/2022","qualification": "GCSE","examCode": "1MA1 1F","subject": "Mathematics","title": "Paper 1 (Non-Calculator) Foundation Tier","amPM": "AM","duration": "1h 30m"},
{"date": "20/05/2022","qualification": "GCSE","examCode": "1MA1 1H","subject": "Mathematics","title": "Paper 1 (Non-Calculator) Higher Tier","amPM": "AM","duration": "1h 30m"},
{"date": "07/06/2022","qualification": "GCSE","examCode": "1MA1 2F","subject": "Mathematics","title": "Paper 2 (Calculator) Foundation Tier","amPM": "AM","duration": "1h 30m"},
{"date": "07/06/2022","qualification": "GCSE","examCode": "1MA1 2H","subject": "Mathematics","title": "Paper 2 (Calculator) Higher Tier","amPM": "AM","duration": "1h 30m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1MA1 3F","subject": "Mathematics","title": "Paper 3 (Calculator) Foundation Tier","amPM": "AM","duration": "1h 30m"},
{"date": "13/06/2022","qualification": "GCSE","examCode": "1MA1 3H","subject": "Mathematics","title": "Paper 3 (Calculator) Higher Tier","amPM": "AM","duration": "1h 30m"},
{"date": "22/06/2022","qualification": "GCSE","examCode": "1MU0 03","subject": "Music","title": "Component 3: Appraising","amPM": "AM","duration": "1h 45m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PN0 1F","subject": "Persian","title": "Paper 1: Listening and understanding in Persian Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PN0 1H","subject": "Persian","title": "Paper 1: Listening and understanding in Persian Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PN0 3F","subject": "Persian","title": "Paper 3: Reading and understanding in Persian Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PN0 3H","subject": "Persian","title": "Paper 3: Reading and understanding in Persian Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "27/06/2022","qualification": "GCSE","examCode": "1PN0 4F","subject": "Persian","title": "Paper 4: Writing in Persian Foundation Tier","amPM": "AM","duration": "1h 20m"},
{"date": "27/06/2022","qualification": "GCSE","examCode": "1PN0 4H","subject": "Persian","title": "Paper 4: Writing in Persian Higher Tier","amPM": "AM","duration": "1h 25m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "1PE0 01","subject": "Physical Education","title": "Component 1: Fitness and Body Systems","amPM": "PM","duration": "1h 45m"},
{"date": "10/06/2022","qualification": "GCSE","examCode": "1PE0 02","subject": "Physical Education","title": "Component 2: Health and Performance","amPM": "PM","duration": "1h 15m"},
{"date": "24/05/2022","qualification": "GCSE","examCode": "3PE0 01","subject": "Physical Education (Short Course)","title": "Component 1: Theory","amPM": "PM","duration": "1h 30m"},
{"date": "09/06/2022","qualification": "GCSE","examCode": "1PH0 1F","subject": "Physics","title": "Paper 1 Foundation Tier","amPM": "PM","duration": "1h 45m"},
{"date": "09/06/2022","qualification": "GCSE","examCode": "1PH0 1H","subject": "Physics","title": "Paper 1 Higher Tier","amPM": "PM","duration": "1h 45m"},
{"date": "23/06/2022","qualification": "GCSE","examCode": "1PH0 2F","subject": "Physics","title": "Paper 2 Foundation Tier","amPM": "AM","duration": "1h 45m"},
{"date": "23/06/2022","qualification": "GCSE","examCode": "1PH0 2H","subject": "Physics","title": "Paper 2 Higher Tier","amPM": "AM","duration": "1h 45m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PG0 1F","subject": "Portuguese","title": "Paper 1: Listening and understanding in Portuguese Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PG0 1H","subject": "Portuguese","title": "Paper 1: Listening and understanding in Portuguese Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PG0 3F","subject": "Portuguese","title": "Paper 3: Reading and understanding in Portuguese Foundation Tier","amPM": "PM","duration": "0h 45m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1PG0 3H","subject": "Portuguese","title": "Paper 3: Reading and understanding in Portuguese Higher Tier","amPM": "PM","duration": "1h 00m"},
{"date": "27/06/2022","qualification": "GCSE","examCode": "1PG0 4F","subject": "Portuguese","title": "Paper 4: Writing in Portuguese Foundation Tier","amPM": "AM","duration": "1h 15m"},
{"date": "27/06/2022","qualification": "GCSE","examCode": "1PG0 4H","subject": "Portuguese","title": "Paper 4: Writing in Portuguese Higher Tier","amPM": "AM","duration": "1h 20m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1PS0 01","subject": "Psychology","title": "Paper 1","amPM": "PM","duration": "1h 45m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1PS0 02","subject": "Psychology","title": "Paper 2","amPM": "PM","duration": "1h 20m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "1RA0 1A-1C","subject": "Religious Studies A","title": "Paper 1: Area of Study 1 – Study of Religion","amPM": "AM","duration": "1h 45m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "1RA0 2A-2G","subject": "Religious Studies A","title": "Paper 2: Area of Study 2 – Study of Second Religion","amPM": "PM","duration": "0h 50m"},
{"date": "08/06/2022","qualification": "GCSE","examCode": "1RA0 3A-3C","subject": "Religious Studies A","title": "Paper 3: Area of Study 3 – Philosophy and Ethics","amPM": "PM","duration": "0h 50m"},
{"date": "08/06/2022","qualification": "GCSE","examCode": "1RA0 4A-4B","subject": "Religious Studies A","title": "Paper 4: Area of Study 4 – Textual Studies","amPM": "PM","duration": "0h 50m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "3RA0 01","subject": "Religious Studies A (Short Course)","title": "Paper 1: Area of Study 1 – Study of Catholic Christianity","amPM": "AM","duration": "0h 50m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "3RA0 02","subject": "Religious Studies A (Short Course)","title": "Paper 2: Area of Study 2 – Study of Christianity","amPM": "AM","duration": "0h 50m"},
{"date": "08/06/2022","qualification": "GCSE","examCode": "3RA0 03","subject": "Religious Studies A (Short Course)","title": "Paper 3: Area of Study 3 – Study of Islam","amPM": "PM","duration": "0h 50m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "3RA0 04","subject": "Religious Studies A (Short Course)","title": "Paper 4: Area of Study 4 – Study of Judaism","amPM": "PM","duration": "0h 50m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "1RB0 1A-1G","subject": "Religious Studies B","title": "Paper 1: Area of Study 1 – Religion and Ethics","amPM": "AM","duration": "1h 45m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "1RB0 2A-2G","subject": "Religious Studies B","title": "Paper 2: Area of Study 2 – Religion, Peace and Conflict","amPM": "PM","duration": "1h 45m"},
{"date": "08/06/2022","qualification": "GCSE","examCode": "1RB0 3A-3G","subject": "Religious Studies B","title": "Paper 3: Area of Study 3 – Religion, Philosophy and Social Justice","amPM": "PM","duration": "1h 45m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "3RB0 1A-1G","subject": "Religious Studies B (Short Course)","title": "Paper 1: Area of Study 1 – Religion and Ethics","amPM": "AM","duration": "0h 50m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "3RB0 2A-2G","subject": "Religious Studies B (Short Course)","title": "Paper 2: Area of Study 2 – Religion, Peace and Conflict","amPM": "PM","duration": "0h 50m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1RU0 1F","subject": "Russian","title": "Paper 1: Listening and understanding in Russian Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1RU0 1H","subject": "Russian","title": "Paper 1: Listening and understanding in Russian Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1RU0 3F","subject": "Russian","title": "Paper 3: Reading and understanding in Russian Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "15/06/2022","qualification": "GCSE","examCode": "1RU0 3H","subject": "Russian","title": "Paper 3: Reading and understanding in Russian Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "28/06/2022","qualification": "GCSE","examCode": "1RU0 4F","subject": "Russian","title": "Paper 4: Writing in Russian Foundation Tier","amPM": "AM","duration": "1h 20m"},
{"date": "28/06/2022","qualification": "GCSE","examCode": "1RU0 4H","subject": "Russian","title": "Paper 4: Writing in Russian Higher Tier","amPM": "AM","duration": "1h 25m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "1SP0 1F","subject": "Spanish","title": "Paper 1: Listening and understanding in Spanish Foundation Tier","amPM": "AM","duration": "0h 35m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "1SP0 1H","subject": "Spanish","title": "Paper 1: Listening and understanding in Spanish Higher Tier","amPM": "AM","duration": "0h 45m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "1SP0 3F","subject": "Spanish","title": "Paper 3: Reading and understanding in Spanish Foundation Tier","amPM": "AM","duration": "0h 45m"},
{"date": "26/05/2022","qualification": "GCSE","examCode": "1SP0 3H","subject": "Spanish","title": "Paper 3: Reading and understanding in Spanish Higher Tier","amPM": "AM","duration": "1h 00m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1SP0 4F","subject": "Spanish","title": "Paper 4: Writing in Spanish Foundation Tier","amPM": "AM","duration": "1h 15m"},
{"date": "17/06/2022","qualification": "GCSE","examCode": "1SP0 4H","subject": "Spanish","title": "Paper 4: Writing in Spanish Higher Tier","amPM": "AM","duration": "1h 20m"},
{"date": "14/06/2022","qualification": "GCSE","examCode": "1ST0 1F","subject": "Statistics","title": "Paper 1 Foundation Tier","amPM": "PM","duration": "1h 30m"},
{"date": "14/06/2022","qualification": "GCSE","examCode": "1ST0 1H","subject": "Statistics","title": "Paper 1 Higher Tier","amPM": "PM","duration": "1h 30m"},
{"date": "24/06/2022","qualification": "GCSE","examCode": "1ST0 2F","subject": "Statistics","title": "Paper 2 Foundation Tier","amPM": "AM","duration": "1h 30m"},
{"date": "24/06/2022","qualification": "GCSE","examCode": "1ST0 2H","subject": "Statistics","title": "Paper 2 Higher Tier","amPM": "AM","duration": "1h 30m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "1TU0 1F","subject": "Turkish","title": "Paper 1: Listening and understanding in Turkish Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "1TU0 1H","subject": "Turkish","title": "Paper 1: Listening and understanding in Turkish Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "1TU0 3F","subject": "Turkish","title": "Paper 3: Reading and understanding in Turkish Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "16/05/2022","qualification": "GCSE","examCode": "1TU0 3H","subject": "Turkish","title": "Paper 3: Reading and understanding in Turkish Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1TU0 4F","subject": "Turkish","title": "Paper 4: Writing in Turkish Foundation Tier","amPM": "PM","duration": "1h 20m"},
{"date": "06/06/2022","qualification": "GCSE","examCode": "1TU0 4H","subject": "Turkish","title": "Paper 4: Writing in Turkish Higher Tier","amPM": "PM","duration": "1h 25m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1UR0 1F","subject": "Urdu","title": "Paper 1: Listening and understanding in Urdu Foundation Tier","amPM": "PM","duration": "0h 35m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1UR0 1H","subject": "Urdu","title": "Paper 1: Listening and understanding in Urdu Higher Tier","amPM": "PM","duration": "0h 45m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1UR0 3F","subject": "Urdu","title": "Paper 3: Reading and understanding in Urdu Foundation Tier","amPM": "PM","duration": "0h 50m"},
{"date": "17/05/2022","qualification": "GCSE","examCode": "1UR0 3H","subject": "Urdu","title": "Paper 3: Reading and understanding in Urdu Higher Tier","amPM": "PM","duration": "1h 05m"},
{"date": "07/06/2022","qualification": "GCSE","examCode": "1UR0 4F","subject": "Urdu","title": "Paper 4: Writing in Urdu Foundation Tier","amPM": "PM","duration": "1h 20m"},
{"date": "07/06/2022","qualification": "GCSE","examCode": "1UR0 4H","subject": "Urdu","title": "Paper 4: Writing in Urdu Higher Tier","amPM": "PM","duration": "1h 25m"},
];

const OCR_GCSE_DATA = [
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J125/01","subject": "Religious Studies","title": "Religion, philosophy and ethics in the modern world","amPM": "AM","duration": "2h 00m "},
    {"date": "20/05/2022","qualification": "GCSE","examCode": "J198/11","subject": "Ancient History","title": "The Persian empire","amPM": "PM","duration": "1h 00m "},
    {"date": "20/05/2022","qualification": "GCSE","examCode": "J198/12","subject": "Ancient History","title": "Greek depth study","amPM": "PM","duration": "0h 45m "},
    {"date": "13/06/2022","qualification": "GCSE","examCode": "J198/21","subject": "Ancient History","title": "The foundations of Rome","amPM": "PM","duration": "1h 00m "},
    {"date": "13/06/2022","qualification": "GCSE","examCode": "J198/22","subject": "Ancient History","title": "Roman depth study","amPM": "PM","duration": "0h 45m "},
    {"date": "18/05/2022","qualification": "GCSE","examCode": "J199/11","subject": "Classical Civilisation","title": "Myth and religion","amPM": "PM","duration": "1h 30m "},
    {"date": "18/05/2022","qualification": "GCSE","examCode": "J199/12","subject": "Classical Civilisation","title": "Women in the ancient world","amPM": "PM","duration": "1h 30m "},
    {"date": "10/06/2022","qualification": "GCSE","examCode": "J199/21","subject": "Classical Civilisation","title": "The Homeric world","amPM": "PM","duration": "1h 30m "},
    {"date": "10/06/2022","qualification": "GCSE","examCode": "J199/22","subject": "Classical Civilisation","title": "Roman city life","amPM": "PM","duration": "1h 30m "},
    {"date": "10/06/2022","qualification": "GCSE","examCode": "J199/23","subject": "Classical Civilisation","title": "War and warfare","amPM": "PM","duration": "1h 30m "},
    {"date": "25/05/2022","qualification": "GCSE","examCode": "J200/01","subject": "Media Studies","title": "Television and promoting media","amPM": "PM","duration": "1h 45m "},
    {"date": "14/06/2022","qualification": "GCSE","examCode": "J200/02","subject": "Media Studies","title": "Music and news","amPM": "PM","duration": "1h 15m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J203/01","subject": "Psychology","title": "Studies and applications in psychology 1","amPM": "PM","duration": "1h 30m "},
    {"date": "06/06/2022","qualification": "GCSE","examCode": "J203/02","subject": "Psychology","title": "Studies and applications in psychology 2","amPM": "PM","duration": "1h 30m "},
    {"date": "20/05/2022","qualification": "GCSE","examCode": "J204/01","subject": "Business","title": "Business 1: business activity, marketing and people","amPM": "PM","duration": "1h 30m "},
    {"date": "13/06/2022","qualification": "GCSE","examCode": "J204/02","subject": "Business","title": "Business 2: operations, finance and influences on business","amPM": "PM","duration": "1h 30m "},
    {"date": "18/05/2022","qualification": "GCSE","examCode": "J205/01","subject": "Economics","title": "Introduction to economics","amPM": "PM","duration": "1h 30m "},
    {"date": "06/06/2022","qualification": "GCSE","examCode": "J205/02","subject": "Economics","title": "National and international economics","amPM": "AM","duration": "1h 30m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J247/01","subject": "Biology","title": "Paper 1 (Foundation tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J247/02","subject": "Biology","title": "Paper 2 (Foundation tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J247/03","subject": "Biology","title": "Paper 3 (Higher tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J247/04","subject": "Biology","title": "Paper 4 (Higher tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J248/01","subject": "Chemistry","title": "Paper 1 (Foundation tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "20/06/2022","qualification": "GCSE","examCode": "J248/02","subject": "Chemistry","title": "Paper 2 (Foundation tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J248/03","subject": "Chemistry","title": "Paper 3 (Higher tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "20/06/2022","qualification": "GCSE","examCode": "J248/04","subject": "Chemistry","title": "Paper 4 (Higher tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J249/01","subject": "Physics","title": "Paper 1 (Foundation tier)","amPM": "PM","duration": "1h 45m "},
    {"date": "23/06/2022","qualification": "GCSE","examCode": "J249/02","subject": "Physics","title": "Paper 2 (Foundation tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J249/03","subject": "Physics","title": "Paper 3 (Higher tier)","amPM": "PM","duration": "1h 45m "},
    {"date": "23/06/2022","qualification": "GCSE","examCode": "J249/04","subject": "Physics","title": "Paper 4 (Higher tier)","amPM": "AM","duration": "1h 45m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J250/01","subject": "Combined Science","title": "Paper 1 (Biology) (Foundation)","amPM": "AM","duration": "1h 10m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J250/02","subject": "Combined Science","title": "Paper 2 (Biology) (Foundation)","amPM": "AM","duration": "1h 10m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J250/03","subject": "Combined Science","title": "Paper 3 (Chemistry) (Foundation)","amPM": "AM","duration": "1h 10m "},
    {"date": "20/06/2022","qualification": "GCSE","examCode": "J250/04","subject": "Combined Science","title": "Paper 4 (Chemistry) (Foundation)","amPM": "AM","duration": "1h 10m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J250/05","subject": "Combined Science","title": "Paper 5 (Physics) (Foundation)","amPM": "PM","duration": "1h 10m "},
    {"date": "23/06/2022","qualification": "GCSE","examCode": "J250/06","subject": "Combined Science","title": "Paper 6 (Physics) (Foundation)","amPM": "AM","duration": "1h 10m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J250/07","subject": "Combined Science","title": "Paper 7 (Biology) (Higher)","amPM": "AM","duration": "1h 10m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J250/08","subject": "Combined Science","title": "Paper 8 (Biology) (Higher)","amPM": "AM","duration": "1h 10m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J250/09","subject": "Combined Science","title": "Paper 9 (Chemistry) (Higher)","amPM": "AM","duration": "1h 10m "},
    {"date": "20/06/2022","qualification": "GCSE","examCode": "J250/10","subject": "Combined Science","title": "Paper 10 (Chemistry) (Higher)","amPM": "AM","duration": "1h 10m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J250/11","subject": "Combined Science","title": "Paper 11 (Physics) (Higher)","amPM": "PM","duration": "1h 10m "},
    {"date": "23/06/2022","qualification": "GCSE","examCode": "J250/12","subject": "Combined Science","title": "Paper 12 (Physics) (Higher)","amPM": "AM","duration": "1h 10m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J257/01","subject": "Biology","title": "Breadth in biology (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J257/02","subject": "Biology","title": "Depth in biology (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J257/03","subject": "Biology","title": "Breadth in biology (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J257/04","subject": "Biology","title": "Depth in biology (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J258/01","subject": "Chemistry","title": "Breadth in chemistry (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "20/06/2022","qualification": "GCSE","examCode": "J258/02","subject": "Chemistry","title": "Depth in chemistry (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J258/03","subject": "Chemistry","title": "Breadth in chemistry (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "20/06/2022","qualification": "GCSE","examCode": "J258/04","subject": "Chemistry","title": "Depth in chemistry (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J259/01","subject": "Physics","title": "Breadth in physics (Foundation)","amPM": "PM","duration": "1h 45m "},
    {"date": "23/06/2022","qualification": "GCSE","examCode": "J259/02","subject": "Physics","title": "Depth in physics (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J259/03","subject": "Physics","title": "Breadth in physics (Higher)","amPM": "PM","duration": "1h 45m "},
    {"date": "23/06/2022","qualification": "GCSE","examCode": "J259/04","subject": "Physics","title": "Depth in physics (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J260/01","subject": "Combined Science","title": "Biology (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J260/02","subject": "Combined Science","title": "Chemistry (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J260/03","subject": "Combined Science","title": "Physics (Foundation)","amPM": "PM","duration": "1h 45m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J260/04","subject": "Combined Science","title": "Combined science (Foundation)","amPM": "AM","duration": "1h 45m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J260/05","subject": "Combined Science","title": "Biology (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J260/06","subject": "Combined Science","title": "Chemistry (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J260/07","subject": "Combined Science","title": "Physics (Higher)","amPM": "PM","duration": "1h 45m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J260/08","subject": "Combined Science","title": "Combined science (Higher)","amPM": "AM","duration": "1h 45m "},
    {"date": "23/05/2022","qualification": "GCSE","examCode": "J270/01","subject": "Citizenship Studies","title": "Citizenship in perspective","amPM": "PM","duration": "0h 50m "},
    {"date": "14/06/2022","qualification": "GCSE","examCode": "J270/02","subject": "Citizenship Studies","title": "Citizenship in action","amPM": "PM","duration": "1h 45m "},
    {"date": "22/06/2022","qualification": "GCSE","examCode": "J270/03","subject": "Citizenship Studies","title": "Our rights, our society, our world","amPM": "PM","duration": "1h 00m "},
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J277/01","subject": "Computer Science","title": "Computer systems","amPM": "PM","duration": "1h 30m "},
    {"date": "27/05/2022","qualification": "GCSE","examCode": "J277/02","subject": "Computer Science","title": "Computational thinking, algorithms and programming","amPM": "PM","duration": "1h 30m "},
    {"date": "17/05/2022","qualification": "GCSE","examCode": "J282/01","subject": "Latin","title": "Language","amPM": "PM","duration": "1h 30m "},
    {"date": "06/06/2022","qualification": "GCSE","examCode": "J282/02","subject": "Latin","title": "Prose literature A","amPM": "AM","duration": "1h 00m "},
    {"date": "06/06/2022","qualification": "GCSE","examCode": "J282/03","subject": "Latin","title": "Prose literature B","amPM": "AM","duration": "1h 00m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J282/04","subject": "Latin","title": "Verse literature A","amPM": "PM","duration": "1h 00m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J282/05","subject": "Latin","title": "Verse literature B","amPM": "PM","duration": "1h 00m "},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "J282/06","subject": "Latin","title": "Literature and culture","amPM": "PM","duration": "1h 00m "},
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J292/01","subject": "Classical Greek","title": "Language ","amPM": "PM","duration": "1h 30m "},
    {"date": "07/06/2022","qualification": "GCSE","examCode": "J292/02","subject": "Classical Greek","title": "Prose literature A","amPM": "PM","duration": "1h 00m "},
    {"date": "07/06/2022","qualification": "GCSE","examCode": "J292/03","subject": "Classical Greek","title": "Prose literature B","amPM": "PM","duration": "1h 00m "},
    {"date": "16/06/2022","qualification": "GCSE","examCode": "J292/04","subject": "Classical Greek","title": "Verse literature A","amPM": "PM","duration": "1h 00m "},
    {"date": "16/06/2022","qualification": "GCSE","examCode": "J292/05","subject": "Classical Greek","title": "Verse literature B","amPM": "PM","duration": "1h 00m "},
    {"date": "22/06/2022","qualification": "GCSE","examCode": "J292/06","subject": "Classical Greek","title": "Literature and culture","amPM": "PM","duration": "1h 00m "},
    {"date": "20/06/2022","qualification": "GCSE","examCode": "J309/01","subject": "Food Preparation & Nutrition","title": "Food preparation and nutrition","amPM": "PM","duration": "1h 30m "},
    {"date": "15/06/2022","qualification": "GCSE","examCode": "J310/01","subject": "Design and Technology","title": "Principles of design and technology","amPM": "PM","duration": "2h 00m "},
    {"date": "19/05/2022","qualification": "GCSE","examCode": "J316/04","subject": "Drama","title": "Drama: Performance and response","amPM": "PM","duration": "1h 30m "},
    {"date": "18/05/2022","qualification": "GCSE","examCode": "J351/01","subject": "English Language","title": "Communicating information and ideas","amPM": "AM","duration": "2h 00m "},
    {"date": "10/06/2022","qualification": "GCSE","examCode": "J351/02","subject": "English Language","title": "Exploring effects and impact","amPM": "AM","duration": "2h 00m "},
    {"date": "25/05/2022","qualification": "GCSE","examCode": "J352/11","subject": "English Literature","title": "Modern prose or drama","amPM": "AM","duration": "1h 15m "},
    {"date": "25/05/2022","qualification": "GCSE","examCode": "J352/12","subject": "English Literature","title": "19th century prose","amPM": "AM","duration": "0h 50m "},
    {"date": "08/06/2022","qualification": "GCSE","examCode": "J352/21","subject": "English Literature","title": "Poetry across time","amPM": "AM","duration": "1h 15m "},
    {"date": "08/06/2022","qualification": "GCSE","examCode": "J352/22","subject": "English Literature","title": "Shakespeare","amPM": "AM","duration": "0h 50m "},
    {"date": "23/05/2022","qualification": "GCSE","examCode": "J383/01","subject": "Geography","title": "Living in the UK today","amPM": "AM","duration": "1h 00m "},
    {"date": "07/06/2022","qualification": "GCSE","examCode": "J383/02","subject": "Geography","title": "The world around us","amPM": "PM","duration": "0h 45m "},
    {"date": "14/06/2022","qualification": "GCSE","examCode": "J383/03","subject": "Geography","title": "Geographical skills","amPM": "AM","duration": "1h 20m "},
    {"date": "23/05/2022","qualification": "GCSE","examCode": "J384/01","subject": "Geography","title": "Our natural world","amPM": "AM","duration": "1h 00m"},
    {"date": "07/06/2022","qualification": "GCSE","examCode": "J384/02","subject": "Geography","title": "People and society","amPM": "PM","duration": "1h 00m "},
    {"date": "14/06/2022","qualification": "GCSE","examCode": "J384/03","subject": "Geography","title": "Geographical exploration","amPM": "AM","duration": "1h 30m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J410/01","subject": "History","title": "China 1950-1981: The people and the state","amPM": "AM","duration": "1h 00m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J410/02","subject": "History","title": "Germany 1925-1955: The people and the state","amPM": "AM","duration": "1h 00m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J410/05","subject": "History","title": "South Africa 1960-1994: The people and the state","amPM": "AM","duration": "1h 00m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J410/06","subject": "History","title": "The USA 1919-1948: The people and the state","amPM": "AM","duration": "1h 00m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J410/07","subject": "History","title": "The USA 1945-1974: The people and the state","amPM": "AM","duration": "1h 00m "},
    {"date": "16/06/2022","qualification": "GCSE","examCode": "J410/08","subject": "History","title": "Migration to Britain c.1000 to c. 2010","amPM": "AM","duration": "1h 00m "},
    {"date": "16/06/2022","qualification": "GCSE","examCode": "J410/09","subject": "History","title": "Power: Monarchy and democracy in Britain c.1000 to 2014","amPM": "AM","duration": "1h 00m "},
    {"date": "16/06/2022","qualification": "GCSE","examCode": "J410/10","subject": "History","title": "War and British society c.790 to c.2010","amPM": "AM","duration": "1h 00m "},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "J410/11","subject": "History","title": "The impact of Empire on Britain 1688-c.1730 with urban environments: Patterns of migration","amPM": "AM","duration": "1h 15m "},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "J410/12","subject": "History","title": "The English Reformation c.1520-c.1550 with castles: form and function c.1000-1750","amPM": "AM","duration": "1h 15m "},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "J410/13","subject": "History","title": "Personal rule to Restoration 1629-1660 with castles: form and function c.1000-1750","amPM": "AM","duration": "1h 15m "},
    {"date": "19/05/2022","qualification": "GCSE","examCode": "J410/14","subject": "History","title": "International Relations: the changing international order 1918-1975","amPM": "AM","duration": "1h 15m "},
    {"date": "19/05/2022","qualification": "GCSE","examCode": "J411/41","subject": "History","title": "The Norman Conquest, 1065-1087","amPM": "AM","duration": "1h 00m "},
    {"date": "19/05/2022","qualification": "GCSE","examCode": "J411/42","subject": "History","title": "The Elizabethans, 1580-1603","amPM": "AM","duration": "1h 00m "},
    {"date": "19/05/2022","qualification": "GCSE","examCode": "J411/43","subject": "History","title": "Britain in peace and war 1900-1918","amPM": "AM","duration": "1h 00m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J411/51","subject": "History","title": "The people's health, c.1250 to present","amPM": "AM","duration": "1h 00m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J411/52","subject": "History","title": "Crime and punishment, c.1250 to present ","amPM": "AM","duration": "1h 00m "},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "J411/53","subject": "History","title": "Migrants to Britain, c.1250 to to present","amPM": "AM","duration": "1h 00m "},
    {"date": "16/06/2022","qualification": "GCSE","examCode": "J411/61","subject": "History","title": "History around us","amPM": "AM","duration": "1h 00m "},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "J411/71","subject": "History","title": "Viking expansion, c.750-c.1050","amPM": "AM","duration": "1h 00m "},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "J411/72","subject": "History","title": "The Mughal Empire, 1526-1707","amPM": "AM","duration": "1h 00m "},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "J411/73","subject": "History","title": "The making of America, 1789-1900","amPM": "AM","duration": "1h 00m "},
    {"date": "27/06/2022","qualification": "GCSE","examCode": "J411/81","subject": "History","title": "The First Crusade, c.1070-1100","amPM": "PM","duration": "1h 00m "},
    {"date": "27/06/2022","qualification": "GCSE","examCode": "J411/82","subject": "History","title": "Aztecs and the Spanish Conquest 1519-1535","amPM": "PM","duration": "1h 00m "},
    {"date": "27/06/2022","qualification": "GCSE","examCode": "J411/83","subject": "History","title": "Living under Nazi rule, 1933-1945","amPM": "PM","duration": "1h 00m "},
    {"date": "22/06/2022","qualification": "GCSE","examCode": "J536/05","subject": "Music","title": "Listening and appraising","amPM": "AM","duration": "1h 30m "},
    {"date": "20/05/2022","qualification": "GCSE","examCode": "J560/01","subject": "Mathematics","title": "Paper 1 (Foundation tier)","amPM": "AM","duration": "1h 30m "},
    {"date": "07/06/2022","qualification": "GCSE","examCode": "J560/02","subject": "Mathematics","title": "Paper 2 (Foundation tier)","amPM": "AM","duration": "1h 30m "},
    {"date": "13/06/2022","qualification": "GCSE","examCode": "J560/03","subject": "Mathematics","title": "Paper 3 (Foundation tier)","amPM": "AM","duration": "1h 30m "},
    {"date": "20/05/2022","qualification": "GCSE","examCode": "J560/04","subject": "Mathematics","title": "Paper 4 (Higher tier)","amPM": "AM","duration": "1h 30m "},
    {"date": "07/06/2022","qualification": "GCSE","examCode": "J560/05","subject": "Mathematics","title": "Paper 5 (Higher tier)","amPM": "AM","duration": "1h 30m "},
    {"date": "13/06/2022","qualification": "GCSE","examCode": "J560/06","subject": "Mathematics","title": "Paper 6 (Higher tier)","amPM": "AM","duration": "1h 30m "},
    {"date": "24/05/2022","qualification": "GCSE","examCode": "J587/01","subject": "Physical Education","title": "Physical factors affecting performance","amPM": "PM","duration": "1h 00m "},
    {"date": "10/06/2022","qualification": "GCSE","examCode": "J587/02","subject": "Physical Education","title": "Socio-cultural issues and sports psychology","amPM": "PM ","duration": "1h 00m "},
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J625/01","subject": "Religious Studies","title": "Christianity beliefs and teachings & practices","amPM": "AM","duration": "1h 00m "},
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J625/02","subject": "Religious Studies","title": "Islam beliefs and teachings & practices","amPM": "AM","duration": "1h 00m "},
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J625/03","subject": "Religious Studies","title": "Judaism beliefs and teachings & practices","amPM": "AM","duration": "1h 00m "},
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J625/04","subject": "Religious Studies","title": "Buddhism beliefs and teachings & practices","amPM": "AM","duration": "1h 00m "},
    {"date": "16/05/2022","qualification": "GCSE","examCode": "J625/05","subject": "Religious Studies","title": "Hinduism beliefs and teachings & practices","amPM": "AM","duration": "1h 00m "},
    {"date": "26/05/2022","qualification": "GCSE","examCode": "J625/06","subject": "Religious Studies","title": "Religion, philosophy and ethics in the modern world from a Christian perspective","amPM": "PM","duration": "2h 00m "},
    {"date": "26/05/2022","qualification": "GCSE","examCode": "J625/07","subject": "Religious Studies","title": "Religion, philosophy and ethics in the modern world from a Muslim perspective","amPM": "PM","duration": "2h 00m "},
    {"date": "26/05/2022","qualification": "GCSE","examCode": "J625/08","subject": "Religious Studies","title": "Religion, philosophy and ethics in the modern world from a Jewish perspective","amPM": "PM","duration": "2h 00m "},
    {"date": "26/05/2022","qualification": "GCSE","examCode": "J625/09","subject": "Religious Studies","title": "Religion, philosophy and ethics in the modern world from a Buddhist perspective","amPM": "PM","duration": "2h 00m "},
    {"date": "26/05/2022","qualification": "GCSE","examCode": "J625/10","subject": "Religious Studies","title": "Religion, philosophy and ethics in the modern world from a Hindu perspective","amPM": "PM","duration": "2h 00m "},
];

const AQA_GCSE_DATA = [  // TODO: History
    {"date": "23/05/2022","qualification": "GCSE","examCode": "8035/1","subject": "Geography", "title": "Paper 1: Living with the physical environment", "amPM": "AM", "duration": "1h 30m"},
    {"date": "07/06/2022","qualification": "GCSE","examCode": "8035/2","subject": "Geography", "title": "Paper 2: Challenges in the human environment", "amPM": "PM", "duration": "1h 30m"},
    {"date": "14/06/2022","qualification": "GCSE","examCode": "8035/3","subject": "Geography", "title": "Paper 3: Geographical applications", "amPM": "AM", "duration": "1h 00m"},
    {"date": "24/05/2022","qualification": "GCSE","examCode": "8582/1","subject": "Physical Education", "title": "The human body and movement in physcial activity and sport", "amPM": "PM", "duration": "1h 15m"},
    {"date": "10/06/2022","qualification": "GCSE","examCode": "8582/2","subject": "Physical Education", "title": "Socio-cultural influences and well-being in physical activity and sport", "amPM": "PM", "duration": "1h 15m"},
    {"date": "31/05/2022","qualification": "GCSE","examCode": "8582/C","subject": "Physical Education", "title": "Non-exam assessment: Practical performance in physical activity and sport", "amPM": "N/A", "duration": ""},
    {"date": "08/06/2022","qualification": "Level 2 AQA Certificate","examCode": "8365/1","subject": "Further Mathematics", "title": "Paper 1", "amPM": "PM", "duration": "1h 45m"},
    {"date": "22/06/2022","qualification": "Level 2 AQA Certificate","examCode": "8365/2","subject": "Further Mathematics", "title": "Paper 2", "amPM": "PM", "duration": "1h 45m"},
    {"date": "19/05/2022","qualification": "GCSE","examCode": "8145/1B/B","subject": "History", "title": "Paper 1 Section BB: Conflict and tension – The inter-war years, 1918-1939", "amPM": "AM", "duration": "1h 00m"},
    {"date": "09/06/2022","qualification": "GCSE","examCode": "8145/1A/B","subject": "History", "title": "Paper 1 Section AB: Germany, 1890-1945: Democracy and dictatorship", "amPM": "AM", "duration": "1h 00m"},
    {"date": "21/06/2022","qualification": "GCSE","examCode": "8145/2B/C","subject": "History", "title": "Paper 2 Section BC: Elizabethan England, c1568-1603", "amPM": "AM", "duration": "1h 00m"},
];

const EDUQAS_GCSE_DATA = [  // TODO: Drama
    {"date": "18/05/2022","qualification": "GCSE","examCode": "C700U10-1","subject": "English Language", "title": "Component 1", "amPM": "AM", "duration": "1h 45m"},
    {"date": "25/05/2022","qualification": "GCSE","examCode": "C720U10-A","subject": "English Literature", "title": "Component 1", "amPM": "AM", "duration": "2h 00m"},
    {"date": "08/06/2022","qualification": "GCSE","examCode": "C720U20-A","subject": "English Literature", "title": "Component 2", "amPM": "AM", "duration": "2h 00m"},
    {"date": "10/06/2022","qualification": "GCSE","examCode": "C700U20-1","subject": "English Language", "title": "Component 2", "amPM": "AM", "duration": "2h 00m"},
];

const CIE_IGCSE_DATA = [
    {"date": "10/05/2022","qualification": "GCSE/IGCSE","examCode": "0983/12","subject": "Information & Communication Technology", "title": "Written Paper", "amPM": "AM", "duration": "2h 00m"},
];

const TIED_DATA = [
    EDEXCEL_IGCSE_DATA, EDEXCEL_GCSE_DATA, OCR_GCSE_DATA, AQA_GCSE_DATA, EDUQAS_GCSE_DATA, CIE_IGCSE_DATA
];

const BOARD_TABLE = [
    "Edexcel", "Edexcel", "OCR", "AQA", "Eduqas", "CIE"
];

const DO_HIGHLIGHT = [
    "4MA1 1H",
    "4MA1 2H",
    "4CH1 1C",
    "4CH1 2C",
    "4PH1 1P",
    "4PH1 2P",
    "4BI1 1B",
    "4BI1 2B",
    "4FR1 01",
    "4FR1 02",
    "4SP1 01",
    "4SP1 02",
    "4GN1 01",
    "4GN1 02",
    "J277/01",
    "J277/02",
    "J282/01",
    "J282/02",
    "J282/03",
    "J282/04",
    "J282/05",
    "J282/06",
    "J199/11",
    "J199/12",
    "J199/21",
    "J199/22",
    "J199/23",
    "J292/01",
    "J292/02",
    "J292/03",
    "J292/04",
    "J292/05",
    "J292/06",
    "8035/1",
    "8035/2",
    "8035/3",
    "8582/1",
    "8582/2",
    "8582/C",
    "C700U10-1",
    "C720U10-A",
    "C720U20-A",
    "C700U20-1",
    "8365/1",
    "8365/2",
    "8145/1B/B",
    "8145/1A/B",
    "8145/2B/C",
    "0983/12"
];

const mainTable = document.getElementById("main-table");

updateTable("");

function doHighlight(item) {
    if (DO_HIGHLIGHT.includes(item.examCode)) return true;
    return false;
}


function updateTable(query) {
    mainTable.innerHTML = "";
    TIED_DATA.forEach((board, boardIndex) => {
        board.forEach((item, index) => {
            if (query == "" || item.subject.toLowerCase().includes(query)) {
                let currentRow = mainTable.insertRow(-1);
                if (doHighlight(item)) {
                    currentRow.classList.add("highlight");
                }
                
                currentRow.insertCell(0).innerHTML = item.subject;
                currentRow.insertCell(1).innerHTML = item.date;
                currentRow.insertCell(2).innerHTML = item.amPM;
                currentRow.insertCell(3).innerHTML = BOARD_TABLE[boardIndex];
                currentRow.insertCell(4).innerHTML = item.qualification;
                currentRow.insertCell(5).innerHTML = item.examCode;
                currentRow.insertCell(6).innerHTML = item.title;
                currentRow.insertCell(7).innerHTML = item.duration;
            }
        });
    });


}

function updateSearch() {
    const searchInputValue = document.getElementById("subject-input").value.toLowerCase();
    updateTable(searchInputValue);
}
